<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RentSeeder extends Seeder
{
    public function run(): void
    {
        // FK referenciák:
        //   rent_type -> rent_types.id  (1=Lakás, 2=Ház, 3=Garzon)
        //   county    -> counties.id    (20=Budapest, 8=Hajdú-Bihar, 2=Baranya)
        //   city      -> cities.id      (1=Budapest, 2=Debrecen, 4=Pécs)

        DB::table('rents')->insert([
            [
                'owner_id'       => 2,
                'rent_type'      => 1,
                'title'          => 'Felújított lakás a belvárosban',
                'highlighted'    => null,
                'description'    => 'Elegáns, teljesen felújított 2 szobás lakás Budapest szívében. Közel a metróhoz és a főbb bevásárlóközpontokhoz. Berendezett, azonnal beköltözhető.',
                'price'          => 180000,
                'currency'       => 'HUF',
                'county'         => 20,
                'city'           => 1,
                'address'        => 'Váci utca 12. II/4.',
                'area'           => 58.5,
                'bedrooms'       => 2,
                'bathrooms'      => 1,
                'status'         => 'available',
                'defaultimage'   => null,
                'available_from' => '2026-03-01 00:00:00',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'owner_id'       => 3,
                'rent_type'      => 2,
                'title'          => 'Csendes családi ház kerttel',
                'highlighted'    => now(),
                'description'    => 'Debrecen egyik nyugodt utcájában kiadó tágas, 4 szobás családi ház. Nagy kert, dupla garázs, állatbarát környezet. Iskolák és óvoda 5 perc sétára.',
                'price'          => 220000,
                'currency'       => 'HUF',
                'county'         => 8,
                'city'           => 2,
                'address'        => 'Arany János utca 45.',
                'area'           => 120.0,
                'bedrooms'       => 4,
                'bathrooms'      => 2,
                'status'        => 'available',
                'defaultimage'   => null,
                'available_from' => '2026-02-15 00:00:00',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'owner_id'       => 4,
                'rent_type'      => 3,
                'title'          => 'Modern garzon a városközpontban',
                'highlighted'    => null,
                'description'    => 'Pécs belvárosában kiadó modern garzonlakás. Teljesen bútorozott, légkondicionált. Ideális egy főre vagy párnak. Közel az egyetemhez.',
                'price'          => 95000,
                'currency'       => 'HUF',
                'county'         => 2,
                'city'           => 4,
                'address'        => 'Király utca 8. I/2.',
                'area'           => 32.0,
                'bedrooms'       => 1,
                'bathrooms'      => 1,
                'status'         => 'rented',
                'defaultimage'   => null,
                'available_from' => '2026-04-01 00:00:00',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'owner_id'       => 5,
                'rent_type'      => 1,
                'title'          => 'Tágas lakás a Duna partján',
                'highlighted'    => null,
                'description'    => 'Gyönyörű panorámás lakás Budapesten, a Duna partján. 3 szoba, erkély, modern konyha. Ideális családoknak.',
                'price'          => 250000,
                'currency'       => 'HUF',
                'county'         => 20,
                'city'           => 1,
                'address'        => 'Fő utca 25. III/2.',
                'area'           => 85.0,
                'bedrooms'       => 3,
                'bathrooms'      => 2,
                'status'         => 'available',
                'defaultimage'   => null,
                'available_from' => '2026-03-15 00:00:00',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'owner_id'       => 2,
                'rent_type'      => 2,
                'title'          => 'Kis családi ház vidéken',
                'highlighted'    => null,
                'description'    => 'Nyugodt vidéki környezetben kiadó 3 szobás ház. Kert, garázs, közel a természethez.',
                'price'          => 150000,
                'currency'       => 'HUF',
                'county'         => 8,
                'city'           => 2,
                'address'        => 'Kossuth utca 10.',
                'area'           => 90.0,
                'bedrooms'       => 3,
                'bathrooms'      => 1,
                'status'         => 'available',
                'defaultimage'   => null,
                'available_from' => '2026-04-01 00:00:00',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'owner_id'       => 3,
                'rent_type'      => 3,
                'title'          => 'Stúdió lakás diákoknak',
                'highlighted'    => null,
                'description'    => 'Kis, de praktikus garzonlakás Pécsen. Olcsó, központi helyen, diákoknak ideális.',
                'price'          => 70000,
                'currency'       => 'HUF',
                'county'         => 2,
                'city'           => 4,
                'address'        => 'Rákóczi út 5. I/1.',
                'area'           => 25.0,
                'bedrooms'       => 1,
                'bathrooms'      => 1,
                'status'         => 'rented',
                'defaultimage'   => null,
                'available_from' => '2026-05-01 00:00:00',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'owner_id'       => 4,
                'rent_type'      => 1,
                'title'          => 'Luxus lakás a hegyekben',
                'highlighted'    => now(),
                'description'    => 'Prémium lakás Budapest egyik legjobb részén. 4 szoba, jacuzzi, panoráma.',
                'price'          => 400000,
                'currency'       => 'HUF',
                'county'         => 20,
                'city'           => 1,
                'address'        => 'Hegy utca 50. V/3.',
                'area'           => 150.0,
                'bedrooms'       => 4,
                'bathrooms'      => 3,
                'status'         => 'available',
                'defaultimage'   => null,
                'available_from' => '2026-02-20 00:00:00',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'owner_id'       => 5,
                'rent_type'      => 2,
                'title'          => 'Régi ház felújítva',
                'highlighted'    => null,
                'description'    => 'Szép, felújított régi ház Debrecenben. Történelmi hangulat, modern kényelem.',
                'price'          => 190000,
                'currency'       => 'HUF',
                'county'         => 8,
                'city'           => 2,
                'address'        => 'Ó utca 15.',
                'area'           => 100.0,
                'bedrooms'       => 3,
                'bathrooms'      => 2,
                'status'         => 'available',
                'defaultimage'   => null,
                'available_from' => '2026-03-10 00:00:00',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'owner_id'       => 2,
                'rent_type'      => 3,
                'title'          => 'Kompakt lakás fiataloknak',
                'highlighted'    => null,
                'description'    => 'Modern, kompakt garzon Pécs központjában. Fiatal pároknak vagy egyedülállóknak.',
                'price'          => 85000,
                'currency'       => 'HUF',
                'county'         => 2,
                'city'           => 4,
                'address'        => 'Széchenyi tér 3. II/5.',
                'area'           => 35.0,
                'bedrooms'       => 1,
                'bathrooms'      => 1,
                'status'         => 'rented',
                'defaultimage'   => null,
                'available_from' => '2026-04-15 00:00:00',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'owner_id'       => 3,
                'rent_type'      => 1,
                'title'          => 'Középkori lakás',
                'highlighted'    => null,
                'description'    => 'Egyedi, középkori stílusú lakás Budapest óvárosában. 2 szoba, boltíves mennyezet.',
                'price'          => 200000,
                'currency'       => 'HUF',
                'county'         => 20,
                'city'           => 1,
                'address'        => 'Vár utca 7. I/3.',
                'area'           => 65.0,
                'bedrooms'       => 2,
                'bathrooms'      => 1,
                'status'         => 'available',
                'defaultimage'   => null,
                'available_from' => '2026-03-20 00:00:00',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}
